### ISSUE TITLE
tests: create a model theater and mission

### ISSUE THREAD

**Issue by jtoppins** [jtoppins/dct#130]
Create a model theater and mission of correct templates and regions containing 4 airbases:
  * a carrier with player spawns
  * a blue airbase with player spawns
  * a red airbase with player spawns
  * an airbase with both blue and red spawns

This will double as both an example of what DCT can offer and a theater to be used to run unit-tests on. The theater needs to be on the default Caucasus map and light weight, maybe only 3 templates per side.

**Comment by wheelyjoe** [comment]
I would like to be assigned this work please.

**Comment by Kijaxu** [comment]
Initial version of this added to my repo DCTDemoTheater. 

Remaining todo:
Add one of each asset type.
Expand theater readme with design advice.

After this I will update with new features as they are added to DCT.

**Comment by jtoppins** [comment]
@Kijaxu got a link? I would like the theater an mission to be a part of the dct repo. That way the unit tests can directly reference the config, mission and templates.

**Comment by jtoppins** [comment]
I am going to incorporate the demo theater directly into the DCT project. That way when someone downloads a release they will also get the demo theater too.
