### ISSUE TITLE
template: coalition must be a number not a string

### ISSUE THREAD

**Issue by jtoppins** [jtoppins/dct#135]
The documentation for coalition[1] says it needs to be a string however the code only accepts a number. It would probably be good to make the code accept only a string value so it is easier for humans to define the coalition.

[1] https://github.com/jtoppins/dct/blob/master/doc/03-designer.md#coalition

**Comment by wheelyjoe** [comment]
@Kijaxu and I

**Comment by ricmzn** [comment]
It's possible to fix this with the recently-updated lua-libs v6 by removing the key type from and letting `checkside` validate the type of the value, ie: https://github.com/ricmzn/dct/blob/master/src/dct/templates/Template.lua#L191
