### ISSUE TITLE
Building ID's not recognised

### ISSUE THREAD

**Issue by wheelyjoe** [jtoppins/dct#140]
2021-03-06 01:04:49.898 INFO    SCRIPTING: DCT|Theater: isStateValid(); state object nil
2021-03-06 01:04:49.898 INFO    SCRIPTING: DCT|Theater: generating new theater
2021-03-06 01:04:49.909 INFO    SCRIPTING: DEBUG-DCT|Asset: StaticAsset(uae_2_testBldg) - adding handler(AssetManager.onDCSEvent)
2021-03-06 01:04:49.909 INFO    SCRIPTING: DEBUG-DCT|AssetManager: Adding object names for 'uae_2_testBldg'
2021-03-06 01:04:49.909 INFO    SCRIPTING: DEBUG-DCT|AssetManager:     + 108789818
2021-03-06 01:04:49.909 ERROR   SCRIPTING: DCT|Theater: protected call - [string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\goals\DamageGoal.lua"]:65: Scenery object doesn't exist
stack traceback:
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:365: in function <[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:363>
	[C]: in function 'getlife'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\goals\DamageGoal.lua"]:65: in function '_afterspawn'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\goals\BaseGoal.lua"]:50: in function 'onSpawn'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\assets\StaticAsset.lua"]:238: in function '_spawn'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\assets\StaticAsset.lua"]:247: in function 'spawn'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:200: in function 'loadOrGenerate'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:211: in function <[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:207>
	(tail call): ?
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Command.lua"]:45: in function 'execute'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:344: in function '_exec'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:368: in function <[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:367>
	[C]: in function 'xpcall'
	[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:371: in function <[string "C:\Users\wheel\Saved Games\DCS.openbeta\Mods\tech\DCT\lua\dct\Theater.lua"]:362>
2021-03-06 01:04:50.380 INFO    SCRIPTING: DEBUG-DCT|Theater: exec(); time taken: 0.00ms; cmds executed: 0

(Uploaded file had to be converted to .txt to upload)
[testBldg.txt](https://github.com/jtoppins/dct/files/6094468/testBldg.txt)

Latest DCT release and DCS version 2.5.6.61527

Building ID does exist, tested via mission editor.

**Comment by wheelyjoe** [comment]
Seems sceneryObject.getLife() doesn't currently work in DCS scripting engine and is causing issues. 

Either hope for fix on ED's end, or remove use of getLife() for buildings and rely on total destruction alone.

**Comment by jtoppins** [comment]
Commit 575235f4438fd4ddc49439a4a8352871b0144e65 merged into master fixed this issue.
