### ISSUE TITLE
Allow custom codenames for templates

### ISSUE THREAD

**Issue by ricmzn** [jtoppins/dct#146]
Templates could have custom codenames defined in the .dct file, instead of picking from a random codename list, enabling the following:

* Repeatable names (easily identify known objectives after a state reset)
* Easier bug tracking (name given to player can also be found in the .dct file of the template)

This would be most useful for strategic assets, which are unique, and thus the codename would also guaranteed to be unique if carefully defined by the mission designer.

An example would be in the .dct file of a template:

`codename = "Milan"`

And so that template, whenever assigned as a mission by the mission commander, would always be called Milan in the briefing and on the target marker. An undefined codename would default to picking from codenamedb.lua.

**Comment by jtoppins** [comment]
I like it.

**Comment by wheelyjoe** [comment]
@Kijaxu and I
