### ISSUE TITLE
Helicopters set to takeoff from ground in invisible FARP gets disabled

### ISSUE THREAD

**Issue by Leite465** [jtoppins/dct#148]
As the title says, if i make an invisible FARP and set the helis to takeoff form ground, the slot becomes inacessible, there's not much more to it but that.
I'm uploading the dct files as well.
[heli.zip](https://github.com/jtoppins/dct/files/6176622/heli.zip)

**Comment by jtoppins** [comment]
DCT blocks slots based on their association with an airfield. So there are two bugs;

1. unassociated slots should always be join-able.
2. Figure out some way to associate slots with the invisible FARP.
