### ISSUE TITLE
Implement ability for players to bypass bugged missions

### ISSUE THREAD

**Issue by Kijaxu** [jtoppins/dct#160]
Currently if a mission is bugged and unable to be completed, players have to circumvent this by permanently assigning that mission to a slot and avoiding it. There needs to be some kind of capability for players to flag a mission as bugged and bypass it.
Obviously, big problems arise with the potential to mark any "annoying" or "unwanted" missions as bugged and have them complete as a result, this must be avoided lest players game the system.

I'm struggling to think of a good way to do this at the moment, feel free to provide ideas.

**Comment by jtoppins** [comment]
There is no good way to do this.

**Comment by Kijaxu** [comment]
Would it be possible to add specific F10 menu options to a whitelisted slot such as the Observer or "Game Master" slot?
Players could report a bugged mission, Admins would use this slot to observe the mission in question, verify it is broken, and then use the scratchpad to request manual completion of a set target? 

I'm not sure what information you would need to provide the scratchpad to identify a target, but this seams a feasible option.

**Comment by jtoppins** [comment]
As far as I know game observers are not attached to any group and thus have no access to F10 menu options, thus no scratchpad. Also the only unique ID for a given target is a sometimes very long name. I am not sure how feasible it is to expect someone to type in the name.

**Comment by jtoppins** [comment]
I am not sure this is needed anymore? As in the master branch we have periodic checking of assets to see if they have met their death goals again.

**Comment by jtoppins** [comment]
Closing.
