### ISSUE TITLE
UI: show breakdown of loaded weapon points

### ISSUE THREAD

**Issue by ricmzn** [jtoppins/dct#173]
Right now, the payload limitation system only shows the total points for the current loadout, with no indication of what each loaded weapon costs and what's breaking the limit, especially if there is a forbidden weapon (ie. the Mig-21 nuke) loaded.

The idea would be to display the current point totals and whether you're allowed to take off, plus a table breaking down the costs like so:

```
A/G Points: 30/60
A/A Points: 10/20

You are allowed to depart.
---
# A/G Weapons
AGM-65E           2x * 15pts = 30pts
Mk-83             4x *  0pts = 0pts
---
# A/A Weapons
AIM-120C          2x *  5pts = 10pts
AIM-9X            2x *  0pts = 0pts
```

Of course, this can be solved by looking at the mission documentation, but some notoriously difficult players forget do so, and also, if there is a difference between the docs and the server settings, players can get confused. DCT has the last word on allowed payloads, so I believe it makes sense for it to also show you what the loaded weapons cost individually.

**Comment by jtoppins** [comment]
It is an interesting idea, you would need to modify `totalPayload()`[1] function to return a total table that contains more data. I would recommend a `payload` field:

```
total[v] = {
	["current"] = 0,
	["max"]     = limits[v],
	["payload"] = { <id> = <count>, },
}
```

Where `<id>` is the typename of the weapon and `<count>` is the number encountered. Then you would need to modify the `CheckPayloadCmd`[2] to support the new data.

[1] https://github.com/jtoppins/dct/blob/master/src/dct/systems/loadouts.lua#L14
[2] https://github.com/jtoppins/dct/blob/master/src/dct/ui/cmds.lua#L131

**Comment by jtoppins** [comment]
If you would like to take this on, let me know and I will assign the bug to you.

**Comment by ricmzn** [comment]
I'll take it, but I'm not sure if I can start it this week.

**Comment by jtoppins** [comment]
no worries.

**Comment by ricmzn** [comment]
Should the display of the breakdown be disabled for players in the air? Working on it, and it can be used to see what weapons you still have any time, and I'm unsure whether that would be considered "cheating" in a hard core internal view only server (which, AFAIK, no such user of DCT exists yet).

**Comment by jtoppins** [comment]
Yes some of the UI commands we need to disable once the player is in the air. I would not worry about it initially though. We should be able to do this later in a generic way.

**Comment by ricmzn** [comment]
A feature has been developed separately in https://github.com/ricmzn/dct/tree/feature-loadout-breakdown and it will be tested on the server before this is cleaned up and submitted as a PR.

Example:
![image](https://user-images.githubusercontent.com/6194377/116453719-96b35400-a835-11eb-9df1-794bb5895711.png)

(FORBIDDEN) is used to denote weapons with a cost higher or equal than `enum.WPNINFCOST` for additional player feedback (so they know why a weapon costs more points than they can ever have).

Another feature, separate to this one, has been made to periodically check for player loadouts and warn them on the ground, as well as give them time to jettison weapons when mistakenly taking off with disallowed loadouts, but I think we need to analyze its impact on DCT as a whole before that is considered for an upstream merge, as it currently relies on a separate timer (outside of the DCT theater update loop) to work.

**Comment by jtoppins** [comment]
I would just replace the `2 * 5000 pts = 10000 pts` with `FORBIDDEN` as there is no reason to even show the calculation if the individual cost of the weapon is greater then the total allowed cost.

> Another feature, separate to this one, has been made to periodically check for player loadouts and warn them on the ground, as well as give them time to jettison weapons when mistakenly taking off with disallowed loadouts, but I think we need to analyze its impact on DCT as a whole before that is considered for an upstream merge, as it currently relies on a separate timer (outside of the DCT theater update loop) to work.

I would create a separate bug for this additional feature. No reason to have this bug feature creep.
