### ISSUE TITLE
Implement Deep Strike Mission Type

### ISSUE THREAD

**Issue by Kijaxu** [jtoppins/dct#33]
Implementation of a specific type of mission called "Deep Strike" that will entail the particularly long sorties to the northern parts of the Iranian Mainland so that players can make a specific decision about whether or not they want to fly a potentially 2hr+ sortie.

**Comment by jtoppins** [comment]
This is a mission type but what kind of assets would be targeted by it? There is no distinction as far as distance concerning assets, for example it is not the case that only factories are in a given place. Meaning only factories would be assigned to a "deep strike" mission.

Am not sure this is actually the solution wanted either. It seems more like distance should be taken into consideration during target assignment, more specifically time, which is airframe specific. Would it be more acceptable to allow the player to specify how long of a mission they wish to fly? Maybe giving them the option to specify a "normal" or "long" mission? If the player specifies a willingness to fly "long" missions all that does is remove the limit criteria to limit predicted mission time to less than X hours. That way the mission designer can specify through DCT's settings what the maximum "normal"/"average" mission time would be. This would allow us to keep asset types non-geographically specific. Thoughts?

**Comment by Kijaxu** [comment]
To be honest, however you wish to approach the issue is fine by me. An opt-in/opt-out system for extended range missions works, just so long as players 100% have the ability to ensure that they will not be asked to fly what are, without doubt, quite long missions.

Secondly, I am hoping that the introduction of dynamic BAI targets and other COIN sorties will help to alleviate the situation when the only remaining strike targets are "deep strikes" as such.

**Comment by wheelyjoe** [comment]
Could be a good use of SCUD targets?

**Comment by Kijaxu** [comment]
Consider this to be an unnecessary implementation due to how the server has developed since opening this ticket. Mission type Strike will simply move as we go and the players will have to step up to deal with it.
