### ISSUE TITLE
Update of templates required to facilitate intel levels

### ISSUE THREAD

**Issue by Kijaxu** [jtoppins/dct#49]
Once intel levels are supported by DCT we will need to update the Templates files to provide each one with an intel level

**Comment by jtoppins** [comment]
This is already supported, in the .dct file just add a key-value pair of "intel" with a value of 0 to 5.

    {
        ...
        ["intel"] = 3,
        ...
    }

The intel level is directly related to the number of decimal places past the degree that are allowed, 84.12345 degrees, as indicated above this would be truncated to 84.123 degrees. Targeting coordinates are anything intel level 3 and above, precision guided munitions need level 4 intel[1].

[1] https://en.wikipedia.org/wiki/Decimal_degrees

**Comment by wheelyjoe** [comment]
In pull request for templates.
