### ISSUE TITLE
move SAM sites on restart

### ISSUE THREAD

**Issue by Kijaxu** [jtoppins/dct#63]
On restart of server (NOT STATE RESET) move non-destroyed SAM targets to another valid location to simulate movement.

Adjust intel level accordingly.

Ensure not despawning an SA-2 and respawning a HAWK. (Check Exclusions usage etc.)

**Comment by jtoppins** [comment]
@Kijaxu what would be easier the ability to define a set of possible positions via a table of coordinates in the template dct definition or to use exclusion zones?

An example of what I mean by a table of possible positions in the template dct file, template.dct:
```
    metadata = {
        positions = {
            {x = 1, y = 4},
            {x = 4, y = 25},
            {x = -34, y = 34},
            {x = 5, y = 0},
        },
        position-method = "random",
    }
```

The `positions` table would define the location where the first unit in the first group would spawn, all other objects within the group would be translated the same amount.

When using exclusion zones we would effectively be respawning the asset each time, so there would be no tracking of if a launcher was taken out. I don't know if this is important.

**Comment by jtoppins** [comment]
With issue #117 I think this is ok for now.
